# Plugin params
solver_plugin: solver_plugins::CeresSolver
ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
ceres_preconditioner: SCHUR_JACOBI
ceres_trust_strategy: LEVENBERG_MARQUARDT
ceres_dogleg_type: TRADITIONAL_DOGLEG
ceres_loss_function: HuberLoss

# ROS Parameters
odom_frame: odom
map_frame: map
base_frame: base_link
scan_topic: /scan
mode: mapping #localization

# if you'd like to immediately start continuing a map at a given pose
# or at the dock, but they are mutually exclusive, if pose is given
# will use pose
# map_file_name: lenna_lab_map_test
# map_start_pose: [0.0, 0.0, 0.0]
#map_start_at_dock: true

debug_logging: false
throttle_scans: 1
transform_publish_period: 0.1 #if 0 never publishes odometry
map_update_interval: 3.0
resolution: 0.05 #0.025
max_laser_range: 6.0 #for rastering images
minimum_time_interval: 0.5
transform_timeout: 0.5 #0.2
tf_buffer_duration: 30
stack_size_to_use: 80000000 #// program needs a larger stack size to serialize large maps 40000000
enable_interactive_mode: true

# General Parameters
use_scan_matching: true
use_scan_barycenter: true
minimum_travel_distance: 0.2
minimum_travel_heading: 0.3  #0.5
scan_buffer_size: 25 #10
scan_buffer_maximum_scan_distance: 7
link_match_minimum_response_fine: 0.4  
link_scan_maximum_distance: 1.5
loop_search_maximum_distance: 3.0 #3
do_loop_closing: true
loop_match_minimum_chain_size: 8          
loop_match_maximum_variance_coarse: 3.0  
loop_match_minimum_response_coarse: 0.4    
loop_match_minimum_response_fine: 0.5

# Correlation Parameters - Correlation Parameters
correlation_search_space_dimension: 1.5 #0.5
correlation_search_space_resolution: 0.05
correlation_search_space_smear_deviation: 0.1

# Correlation Parameters - Loop Closure Parameters
loop_search_space_dimension: 3.0
loop_search_space_resolution: 0.05
loop_search_space_smear_deviation: 0.1

# Scan Matcher Parameters
distance_variance_penalty: 0.5      
angle_variance_penalty: 0.6  

fine_search_angle_offset: 0.00873    #349
coarse_search_angle_offset: 0.0873  
coarse_angle_resolution: 0.0873      
minimum_angle_penalty: 0.8
minimum_distance_penalty: 0.5
use_response_expansion: true